#
# Azure Pipelines configuration for building and testing Jest on Linux, Windows, and macOS.
#

jobs:
  - job: Windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - script: |
          git config --global core.autocrlf false
          git config --global core.symlinks true
        displayName: 'Preserve LF endings and symbolic links on check out'
      - template: .azure-pipelines-steps.yml

variables:
  # Used by chalk. Ensures output from Jest includes ANSI escape characters that are needed to match test snapshots.
  FORCE_COLOR: 1

  # By default, Azure Pipelines clones to an "s" directory, which causes tests to fail due to assumption of Jest being run from a "jest" directory.
  # See packages/jest-message-util/src/index.js PATH_JEST_PACKAGES for more details.
  JEST_DIR: $(Agent.BuildDirectory)/jest

  # Ensures the handful of tests that should be skipped during CI are
  CI: true
